version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/lib/p2p"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[chore](p2p)"
    labels:
      - "dependencies"
      - "rust"
      - "chore"
      - "p2p"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/lib/relay"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[chore](relay-lib)"
    labels:
      - "dependencies"
      - "rust"
      - "chore"
      - "relay-lib"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/lib/relay/.config/docker"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[chore](relay-lib)"
    labels:
      - "dependencies"
      - "chore"
      - "relay-lib"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[chore](monorepo)"
    labels:
      - "dependencies"
      - "github_actions"
      - "chore"
      - "monorepo"
    groups:
      actions:
        patterns:
          - "*"
