# Use cargo-make to run tasks here: https://crates.io/crates/cargo-make

[tasks.format]
description = "Formats the code using unstable features for better import grouping"
workspace = false
command = "cargo"
args = [
     "fmt",
     "--all",
     "--",
     "--config",
     "unstable_features=true",
     "--config",
     "imports_granularity=Crate,group_imports=StdExternalCrate,reorder_imports=true,format_code_in_doc_comments=true",
]

[tasks.check]
description = "Quickly check if the relay compiles"
workspace = false
command = "cargo"
args = ["check", "-p", "iroh-relay", "--features", "server"]

[tasks.build-relay]
description = "Build the relay binary in release mode"
workspace = false
command = "cargo"
args = ["build", "--release", "-p", "iroh-relay", "--features", "server"]

[tasks.run-relay]
description = "Run the relay in dev mode"
workspace = false
command = "cargo"
args = ["run", "-p", "iroh-relay", "--features", "server", "--", "--dev"]

[tasks.test]
description = "Run iroh-relay tests using nextest"
workspace = false
command = "cargo"
args = ["nextest", "run", "-p", "iroh-relay", "--features", "server"]

[tasks.test-all]
description = "Run all tests in the workspace using nextest"
workspace = false
command = "cargo"
args = ["nextest", "run", "--workspace", "--all-features"]
