use std::path::{Path, PathBuf};

use thiserror::Error;

pub mod comic;
pub mod db;
pub mod p2p;
pub mod reader;
pub mod rpc;

pub use reader::ReaderError;

#[derive(Debug, Error)]
pub enum ComicError {
    #[error("Comic already exists in the library.")]
    AlreadyExists,

    #[error("Comic not found.")]
    NotFound,

    #[error("ComicInfo.xml file not found in comic directory or archive.")]
    ComicInfoNotFound,

    #[error("Invalid data: {0}")]
    InvalidRequest(String),

    #[error("Invalid or missing reference to a related record.")]
    IntegrityViolation,

    #[error("System failure while processing the comic: {0}")]
    SystemFailure(String),

    #[error("Filesystem access error: {0}")]
    Io(std::io::Error),
}

#[derive(Debug, Error)]
pub enum DbError {
    #[error("Record not found.")]
    NotFound,

    #[error("Unique constraint violation.")]
    UniqueViolation,

    #[error("Foreign key constraint violation.")]
    ForeignKeyViolation,

    #[error("Check constraint violation.")]
    CheckViolation,

    #[error("Internal database error: {0}")]
    Internal(sqlx::Error),
}

#[derive(Debug, Error)]
pub enum FileError {
    #[error("Extension not allowed: .{0}")]
    ExtensionNotAllowed(String),

    #[error("File not allowed: {0}")]
    FileNameNotAllowed(String),

    #[error("File has no extension.")]
    MissingExtension,

    #[error("Path has no file name.")]
    MissingFileName,

    #[error("File not recognized by any guard: {0}")]
    NotAllowed(String),
}

impl FileError {
    pub fn not_allowed(name: &str) -> Self {
        log::debug!("[FileError] File skipped by scanner: {}", name);
        FileError::NotAllowed(name.to_string())
    }
}

#[derive(Debug, Error)]
pub enum PathError {
    #[error("Access denied: path is outside the allowed directory.")]
    AccessDenied,

    #[error("Path not found or inaccessible: {0}")]
    NotFound(PathBuf),

    #[error("Operation on path failed: {0}")]
    ActionFailed(String),
}

impl PathError {
    pub fn not_found(path: &Path) -> Self {
        log::debug!("[PathError] Path not found: {:?}", path);
        PathError::NotFound(path.to_path_buf())
    }

    pub fn access_denied(canonical: &Path, root: &Path) -> Self {
        log::warn!("[PathError] Access denied: {:?} is outside {:?}", canonical, root);
        PathError::AccessDenied
    }

    pub fn action_failed(path: &Path, msg: impl std::fmt::Display) -> Self {
        log::error!("[PathError] Operation failed on {:?}: {}", path, msg);
        PathError::ActionFailed(msg.to_string())
    }
}

#[derive(Debug, Error)]
pub enum PatternError {
    #[error("Malformed macro: missing closing '}}'.")]
    MalformedMacro,

    #[error("Unknown macro: '{0}'.")]
    UnknownMacro(String),

    #[error("Template must contain exactly one {{chapter}}.")]
    ChapterRequired,

    #[error("Template must contain at most one {{decimal}}.")]
    DecimalDuplicate,

    #[error("Template must contain exactly one {{extension}}.")]
    ExtensionRequired,

    #[error("{{decimal}} must come after {{chapter}}.")]
    DecimalBeforeChapter,

    #[error("{{extension}} must come after {{chapter}}.")]
    ExtensionBeforeChapter,

    #[error("{{extension}} must come after {{decimal}}.")]
    ExtensionBeforeDecimal,

    #[error("Template must end with {{extension}}.")]
    ExtensionNotAtEnd,

    #[error("Template must contain exactly one {{volume}}.")]
    VolumeRequired,

    #[error("Invalid regex pattern generated by template: {0}")]
    InvalidRegex(String),
}

#[derive(Debug, Error)]
pub enum RpcError {
    #[error("failed to serialize message: {0}")]
    Serialize(String),

    #[error("failed to deserialize message: {0}")]
    Deserialize(String),

    #[error("stream error: {0}")]
    Stream(String),
}
