export const NETWORK_COMMANDS = {
	getNetworkStatus: 'get_network_status',
	switchToLocal: 'switch_to_local',
	switchToRelay: 'switch_to_relay',
	getLocalId: 'get_local_id',
	getLocalAddr: 'get_local_addr',
	getLocalDeviceInfo: 'get_local_device_info',
	setLocalDeviceName: 'set_local_device_name',
	getPairedPeers: 'get_paired_peers',
	removePairedPeer: 'remove_paired_peer',
	getRelayInfo: 'get_relay_info',
	setIrohServicesTicket: 'set_iroh_services_ticket',
	clearIrohServicesTicket: 'clear_iroh_services_ticket',
	applyRelaySettings: 'apply_relay_settings',
	connectToPeer: 'connect_to_peer',
	syncHistory: 'sync_history',
	syncFiles: 'sync_files',
	syncAll: 'sync_all',
	syncComic: 'sync_comic',
	queryRemoteLibrary: 'query_remote_library',
	queryRemoteCover: 'query_remote_cover',
	getSyncHistoryLog: 'get_sync_history_log',
	getSecurityStatus: 'get_security_status'
} as const;
