name: "P2P/Release"

on:
  push:
    tags:
      - 'p2p/v*'
  workflow_dispatch:

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib/p2p

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: Build Release
        run: cargo make build-release

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: release-build
          path: lib/p2p/target/release/
