name: "Relay/Tests"

on:
  push:
    branches:
      - develop
    paths:
      - 'lib/relay/**'
      - '.github/workflows/relay-tests.yml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Workspace Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib/relay
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Install cargo-make and nextest
        run: |
          cargo install cargo-make --debug
          curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Check Formatting
        run: cargo make format

      - name: Run All Tests
        run: cargo make test-all
